version: "3"
services:
  backend:
    container_name: nodejs
    restart: always
    build: ./
    env_file: ./src/.env
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - ./error.log:/usr/src/app/error.log
    links:
      - mongo
      - elasticsearch
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.0
    restart: always
    environment:
      - node.name=elasticsearch
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.15.0
    restart: always
    environment:
      - ES_HOST=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

volumes:
  esdata:
    driver: local
